INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (1, 'El Abisinio es un gato con un aspecto bastante salvaje, su mirada y el jaspeado característico de su pelaje recuerdan fácilmente a la fisonomía del puma.', 20, 'sociable y cariñoso', 'Abisinio', 'Pequeño', 3);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (2, 'El American Curl es el gato de las orejas curvadas. Se trata de una raza muy joven, los primeros cruces se iniciaron en 1980. Goza de gran popularidad en Estados Unidos y en Europa poco a poco se va afianzando.', 20, 'Docil', 'American Curl', 'Pequeño', 3);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (3, 'El Angora Turco, a decir de muchos entendidos, podría ser la raza felina más antigua y origen de muchas de las actuales. Lo cierto es que, de estos bellos animales, ya se tiene constancia en varios países del Oriente Próximo desde tiempos Bizantinos.', 20, 'Docil', 'Angora Turco', 'Pequeño', 3);

INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (4, 'Esta es una raza muy antigua, común en toda Francia, utilizada para la caza menor y descrita o citada en varias obras desde el siglo XVI.', 12, 'Equilibrado y sociable', 'Barbet', 'Mediano', 2);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (5, 'Sus criadores pusieron especial cuidado en conseguir un perro que fuera un excelente compañero familiar, seleccionando cuidadosamente los atributos más deseables del American Pit Bull Terrier y del American Stafforshire Terrier.', 12, 'Carácter excelente', 'American Bully', 'Mediano', 2);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (6, 'La talla de los perros japoneses originalmente variaba de pequeña a mediana y no existían razas grandes. A partir de 1603, provenientes de la región Akita, los perros llamados Matagi Akitas', 12, 'calmado, fiel, dócil', 'Akita', 'Mediano', 2);

INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (7,'Es el ave más popular dentro de este tipo de mascotas, gracias a las facilidades que representa cuidarlos, así que es el más indicado para quienes tienen por primera vez un pájaro como mascota', 12, 'Tranquilo, Sociable', 'Perico', 'Pequeño', 4);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (8,'El cantante más conocido de las aves de compañía entra en la lista de los favoritos también, precisamente por sus melodiosos trinos y el intenso color amarillo de sus plumas.', 15, 'buen Humor', 'Canario', 'Pequeño', 4);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (9,'Estos diminutos pajaritos han ido ganando popularidad en los últimos tiempos gracias a su tierna y pequeña figura de tan solo 12 centímetros, su pico y patas de un rojo intenso y sus plumas color crema.', 6, 'Sociables', 'Diamantes Mandarín', 'Pequeño', 4);

INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (10,'El hurón es un roedor que lleva domesticándose desde hace más de 2.500 años. Antiguamente se utilizaba para cazar conejos y aunque hoy su uso principal es como mascota, sigue acompañando a los cazadores ocasionalmente', 10, 'Dormilon, Jugeton', 'Huron', 'Pequeño', 5);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (11,'Por su pequeño tamaño, son considerados mascotas para niños, y si a estos no se les enseña bien cómo tratar y cuidar al animal, a veces las consecuencias pueden ser trágicas', 3, 'Solitario', 'Hamster', 'Pequeño', 5);
INSERT INTO BREEDENTITY (id, description, lifeexpectancy, mood, name, size, specie_id) VALUES (12,'Las chinchillas son unos animales muy sociables y deben vivir en manada, ya que de lo contrario se vuelven animales tristes y sedentarios', 10, 'Sociable', 'Chinchilla', 'Pequeño', 5);